apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: secure-microservice
  template:
    metadata:
      labels:
        app: secure-microservice
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
      containers:
        - name: app
          image: ghcr.io/YOUR_ORG/YOUR_REPO:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: uri
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
